// Generated by gencpp from file planner/GantryPath.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_GANTRYPATH_H
#define PLANNER_MESSAGE_GANTRYPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner
{
template <class ContainerAllocator>
struct GantryPath_
{
  typedef GantryPath_<ContainerAllocator> Type;

  GantryPath_()
    : path()  {
    }
  GantryPath_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::planner::GantryPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::GantryPath_<ContainerAllocator> const> ConstPtr;

}; // struct GantryPath_

typedef ::planner::GantryPath_<std::allocator<void> > GantryPath;

typedef boost::shared_ptr< ::planner::GantryPath > GantryPathPtr;
typedef boost::shared_ptr< ::planner::GantryPath const> GantryPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::GantryPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::GantryPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner::GantryPath_<ContainerAllocator1> & lhs, const ::planner::GantryPath_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner::GantryPath_<ContainerAllocator1> & lhs, const ::planner::GantryPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner::GantryPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::GantryPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::GantryPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::GantryPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::GantryPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::GantryPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::GantryPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48ba10a81da6976bce0a9617ff2a025d";
  }

  static const char* value(const ::planner::GantryPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48ba10a81da6976bULL;
  static const uint64_t static_value2 = 0xce0a9617ff2a025dULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::GantryPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/GantryPath";
  }

  static const char* value(const ::planner::GantryPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::GantryPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] path\n"
;
  }

  static const char* value(const ::planner::GantryPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::GantryPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GantryPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::GantryPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::GantryPath_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_GANTRYPATH_H
