M48
; DRILL file {KiCad (7.0.0-0)} date Saturday, November 04, 2023 at 10:02:22 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-04T22:02:22-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.025Y-3.7006
X5.325Y-5.7506
X5.925Y-3.7506
T2
X3.0315Y-2.3622
X3.0709Y-6.6535
X7.5197Y-2.3622
X7.5197Y-6.6535
T0
M30
